version: "3.3"

services:
  db:
    image: postgres
    hostname: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=todo_db
    ports:
      - "5432:5432"

    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  backend:
    container_name: backend
    build:
      context: todo_server
      dockerfile: Dockerfile
    ports:
      - "8005:8005"
    volumes:
      - type: bind
        source: ./todo_server
        target: /todo_server
    depends_on:
      - db


  frontend:
    container_name: frontend
    build:
      context: todo-client
      dockerfile: Dockerfile
    ports:
      - 80:80
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
